# Generated by Django 5.0.6 on 2024-07-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.city'),
        ),
    ]
